---
title: "Chapter-4 of Forecasting: Principles & Practices"
subtitle: "Judgmental forecasts"
author: "Nikhil Singh"
date: "November 29, 2019"
output: html_document
---

- Research in this area has shown that the accuracy of judgmental forecasting improves when the forecaster has
  - important domain knowledge
  - more timely, up-to-date information

> A judgmental approach can be quick to adjust to such changes, information or events.

There are three general settings in which judgmental forecasting is used:
  - there are no available data, so that statistical methods are not applicable and judgmental forecasting is the only feasible approach
  - data are available, statistical forecasts are generated, and these are then adjusted using judgement
  - data are available and statistical and judgmental forecasts are generated independently and then combined.
  
# Limitations

  - Judgmental forecasts are subjective, and therefore do not come free of bias or limitations.
  - Judgement can be clouded by personal or political agendas, where targets and forecasts
  - Anchoring: Subsequent forecasts tend to converge or be close to an initial familiar reference point.
  
  
# Key principles
  - Set the forecasting task clearly and concisely
  - Implement a systematic approach
  - Document and justify
  - Systematically evaluate forecasts Segregate forecasters and users
  
  
# The Delphi method
Stages of Delphi method:
  1)  A panel of experts is assembled.
  2)  Forecasting tasks/challenges are set and distributed to the experts.
  3)  Experts return initial forecasts and justifications. These are compiled and summarised in order to provide feedback.
  4)  Feedback is provided to the experts, who now review their forecasts in light of the feedback. This step may be iterated until a satisfactory level of consensus is reached.
  5)  Final forecasts are constructed by aggregating the experts' forecasts.
  
# New product forecasting
Judgemental forecasting is usally the only available method for new product forecasting as historical data are unavailable.

### Methods which are commonly applied in practice:
  1)  Sales force composite: forecasts for each outlet/branch/store of a company are generated by salepeople, and are then aggregated.
  2)  Executive opinion
  3)  Customer intentions
  
# Judgemental Adjustments
Judgmental adjustments, like judgmental forecasts, come with biases and limitations, and we must implement methodical strategies in order to minimise them.

  - Use adjustments sparingly: Judgmental adjustments should not aim to correct for a systematic pattern in the data that is thought to have been missed by the statistical model. This has been proven to be ineffective, as forecasters tend to read non-existent patterns in noisy series. Statistical models are much better at taking account of data patterns, and judgmental adjustments only hinder accuracy.
  - Apply a structured approach